### ISSUE TITLE
Change the method name `get_data_qubit` to just `get_qubit` 

### ISSUE THREAD

**Issue by stephendiadamo** [tqsd/QuNetSim#121]
The Host method `get_data_qubit` can be renamed to `get_qubit` for simplicity.

**Comment by WingCode** [comment]
@stephendiadamo Going through the docs, I noticed a `get_data_qubits` [function](https://tqsd.github.io/QuNetSim/components/host.html#qunetsim.components.host.Host.get_data_qubits). Should we also rename `get_data_qubits` to `get_qubits` for simplicity?

**Comment by stephendiadamo** [comment]
@WingCode that makes sense! Yes, I would say to make that change too.

**Comment by stephendiadamo** [comment]
@WingCode it should also be deprecated out, rather than replaced.

**Comment by WingCode** [comment]
@stephendiadamo Are we depreciating [get_data_qubits](https://tqsd.github.io/QuNetSim/components/host.html#qunetsim.components.host.Host.get_data_qubits) in favour of [get_all_qubits_from_host](https://tqsd.github.io/QuNetSim/objects/quantum_storage.html#qunetsim.objects.storage.quantum_storage.QuantumStorage.get_all_qubits_from_host) ?
I am asking because usually with depreciation we include a nice little message for an alternative function which achieves a similar utility or a reason why the function has been deprecated.

**Comment by stephendiadamo** [comment]
@WingCode No, those two methods have two different behaviours. Just we want to deprecate get_data_qubits to get_qubits and get_data_qubit to get_qubit.

**Comment by WingCode** [comment]
@stephendiadamo Forgot to ask, could you assign this issue to me?
