### ISSUE TITLE
what are the best metrics of security checker for QKD

### ISSUE THREAD

**Issue by zemenfes-afk** [tqsd/QuNetSim#124]

**Comment by stephendiadamo** [comment]
Can you please add some context to the question? What have you already looked at? What kind of answer would you like to receive?

**Comment by zemenfes-afk** [comment]
I want to make the analysis of security for both BB84 and B92. For choosing which model to use, can you give some metrics of measurement that can help me to do an experiment... for example error rate, clock rate, speed of channel communication using qubits?

**Comment by stephendiadamo** [comment]
Personally I can't, since I don't work much with cryptography. You could post on the quantum computing stack exchange or maybe one of the forums hosted by UnitaryFund or QOSF.

I think you won't get much feedback here since it's not so active. I'll close this ticket for now since it's more advice on QKD than QuNetSim related.
